/*
 * Shopify Market API - 2019 Intern Challenge
 * Barebones of an online marketplace for the 2019 shopify intern challenge.  This API provides the ability to search through and make purchases from the  product catalog. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mjackson74u@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
